app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.cache import cache_page

from app.apps import AppConfig
from app.views import contacts, ProductListView, ProductDetailView, \
    RecordCreateView, RecordUpdateView, RecordListView, RecordDetailView, \
    RecordDeleteView, ProductCreateView, ProductUpdateWithVersionView, \
    ProductDeleteView, change_is_published, ProductDescriptionUpdateView, \
    ProductCategoryUpdateView, CategoryListView

app_name = AppConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', login_required(contacts), name='contacts'),
    path('product_create/', login_required(ProductCreateView.as_view()), name='create_product'),
    path('product_update/<int:pk>/', login_required(ProductUpdateWithVersionView.as_view()), name='update_product'),
    path('product_update_description/<int:pk>/', login_required(ProductDescriptionUpdateView.as_view()), name='update_product_description'),
    path('product_update_category/<int:pk>/', login_required(ProductCategoryUpdateView.as_view()), name='update_product_category'),
    path('list_category/', login_required(CategoryListView.as_view()), name='list_category'),
    path('<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_card'),
    path('is_published/<int:pk>/', change_is_published, name='change_is_published'),
    path('product_delete/<int:pk>/', login_required(ProductDeleteView.as_view()), name='delete_product'),
    path('records/', RecordListView.as_view(), name='records'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_card'),
    path('records_create/', RecordCreateView.as_view(), name='create_record'),
    path('records_update/<slug:slug>/', RecordUpdateView.as_view(), name='update_record'),
    path('records_delete/<slug:slug>/', RecordDeleteView.as_view(), name='delete_record'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, PasswordChangeView
from django.urls import path
from users.apps import UsersConfig
from users.views import CustomLoginView, UserEditProfileView, \
    CustomRegisterView, CustomPasswordChangeView, user_activation, \
    registration, registration_failed, CustomPasswordResetView, \
    CustomPasswordResetConfirmView, CustomPasswordResetDoneView, \
    CustomPasswordResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', login_required(UserEditProfileView.as_view()), name='profile'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('password/', CustomPasswordChangeView.as_view(), name='reset_password'),
    path('activate/<str:token>/', user_activation, name='activate'),
    path('register_continue/', registration, name='continue_registration'),
    path('register_failed/', registration_failed, name='registration_failed'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<uidb64>/confirm/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

base/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    avatar = models.ImageField(upload_to='users/', **NULLABLE, verbose_name='аватар')
    phone = models.CharField(max_length=25, verbose_name='номер телефона')
    country = models.CharField(max_length=50, verbose_name='страна')
    token = models.CharField(max_length=15, **NULLABLE, verbose_name='токен')
    token_expired = models.DateTimeField(**NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

base/forms.py
from django import forms


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'

            field.help_text = ''

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UsernameField, \
    PasswordResetForm, AuthenticationForm, SetPasswordForm

from base.forms import StyleFormMixin
from users.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class CustomEditUserForm(StyleFormMixin, UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Сохранить изменения'))

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar',)
        field_classes = {'username': UsernameField}


class CustomUserCreationForm(StyleFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Зарегистрироваться'))

    class Meta:
        model = User
        fields = ('email', 'password', 'avatar',)
        # field_classes = {'username': UsernameField}


class CustomAuthenticationForm(StyleFormMixin, AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Войти'))

    class Meta:
        model = User


class CustomChangePasswordForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Сохранить'))


class CustomResetConfirmForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Изменить пароль'))


class CustomPasswordResetForm(StyleFormMixin, PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Сбросить пароль'))

    class Meta:
        model = User

base/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.conf import settings

import datetime
import pytz

from django.contrib.auth.views import LoginView, PasswordChangeView, \
    PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView
from django.views.generic import UpdateView, CreateView

from users.models import User

from users.forms import CustomEditUserForm, CustomUserCreationForm, \
    CustomPasswordResetForm, CustomAuthenticationForm, \
    CustomChangePasswordForm, CustomResetConfirmForm

from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from app.services import send_register_mail, set_registration


class CustomLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = CustomAuthenticationForm


class CustomRegisterView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:continue_registration')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            self.object = set_registration(form, self.object)
            self.object.save()

            send_register_mail(
                message=f'Чтобы завершить регистрацию, перейдите по ссылке:\nhttp://localhost:8000/users/activate/{self.object.token}/',
                email=self.object.email
            )

        return super().form_valid(form)


class UserEditProfileView(UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = CustomEditUserForm
    success_url = reverse_lazy('app:index')

    def get_object(self, queryset=None):
        return self.request.user


class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('app:index')
    template_name = 'users/change_password.html'
    form_class = CustomChangePasswordForm


def user_activation(request, token):
    user = User.objects.filter(token=token).first()

    if user:
        now = datetime.datetime.now((pytz.timezone(settings.TIME_ZONE)))
        if user.token_expired > now:
            user.is_active = True
            user.token = None
            user.token_expired = None
            user.save()

            return redirect(to='/users/')

        user.delete()
    return redirect(to='/users/registration_failed')


def registration(request):
    return render(request, 'users/continue_register.html')


def registration_failed(request):
    return render(request, 'users/registration_failed.html')


class CustomPasswordResetView(PasswordResetView):
    template_name = 'users/reset_password.html'
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')
    email_template_name = 'users/email_reset.html'
    from_email = settings.EMAIL_HOST_USER


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')
    form_class = CustomResetConfirmForm


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/reset_done.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/reset_complete.html'

users/templates/users/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
     <meta charset="UTF-8">
    <title></title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>

/* BASIC */

html {
  background-color: #56baed;
}

body {
  font-family: "Poppins", sans-serif;
  height: 100vh;
}

a {
  color: #92badd;
  display:inline-block;
  text-decoration: none;
  font-weight: 400;
}

h2 {
  text-align: center;
  font-size: 16px;
  font-weight: 600;
  text-transform: uppercase;
  display:inline-block;
  margin: 40px 8px 10px 8px;
  color: #cccccc;
}

h4 {
  text-align: center;
  font-size: 9px;
  font-weight: 500;
  text-transform: uppercase;
  display:inline-block;
  margin: 40px 8px 10px 8px;
  color: #cccccc;
}



/* STRUCTURE */

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

#formContent {
  -webkit-border-radius: 10px 10px 10px 10px;
  border-radius: 10px 10px 10px 10px;
  background: #fff;
  padding: 30px;
  width: 90%;
  max-width: 450px;
  position: relative;
  -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  text-align: center;
}

#formFooter {
  background-color: #f6f6f6;
  border-top: 1px solid #dce8f1;
  padding: 25px;
  text-align: center;
  -webkit-border-radius: 0 0 10px 10px;
  border-radius: 0 0 10px 10px;
}



/* TABS */

h2.inactive {
  color: #cccccc;
}

h2.active {
  color: #0d0d0d;
  border-bottom: 2px solid #5fbae9;
}

{#div.outer {#}
{#  display: table;#}
{#  position: absolute;#}
{#  top: 0;#}
{#  left: 0;#}
{#  height: 100%;#}
{#  width: 100%;#}
{#}#}
{##}
{#div.middle {#}
{#  display: table-cell;#}
{#  vertical-align: middle;#}
{#}#}
{##}
{#div.inner {#}
{#  margin-left: auto;#}
{#  margin-right: auto;#}
{#  width: 600px;#}
{#  /* Whatever width you want */#}
{#}#}

/* FORM TYPOGRAPHY*/
{#p {#}
{#    text-align: center#}
}
input[type=button], input[type=submit], input[type=reset]  {
  background-color: #56baed;
  border: none;
  color: white;
  padding: 15px 80px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  text-transform: uppercase;
  font-size: 13px;
  -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
  margin: 5px 20px 40px 20px;
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
  background-color: #39ace7;
}

input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
  -moz-transform: scale(0.95);
  -webkit-transform: scale(0.95);
  -o-transform: scale(0.95);
  -ms-transform: scale(0.95);
  transform: scale(0.95);
}

input[type=text] {
  background-color: #f6f6f6;
    border: 2px solid #f6f6f6;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

input[type=text]:focus {
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}

input[type=text]:placeholder {
  color: #cccccc;
}



/* ANIMATIONS */

/* Simple CSS3 Fade-in-down Animation */
.fadeInDown {
  -webkit-animation-name: fadeInDown;
  animation-name: fadeInDown;
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}



@-webkit-keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

/* Simple CSS3 Fade-in Animation */
@-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

.fadeIn {
  opacity:0;
  -webkit-animation:fadeIn ease-in 1;
  -moz-animation:fadeIn ease-in 1;
  animation:fadeIn ease-in 1;

  -webkit-animation-fill-mode:forwards;
  -moz-animation-fill-mode:forwards;
  animation-fill-mode:forwards;

  -webkit-animation-duration:1s;
  -moz-animation-duration:1s;
  animation-duration:1s;
}

.fadeIn.first {
  -webkit-animation-delay: 0.4s;
  -moz-animation-delay: 0.4s;
  animation-delay: 0.4s;
}

.fadeIn.second {
  -webkit-animation-delay: 0.6s;
  -moz-animation-delay: 0.6s;
  animation-delay: 0.6s;
}

.fadeIn.third {
  -webkit-animation-delay: 0.8s;
  -moz-animation-delay: 0.8s;
  animation-delay: 0.8s;
}

.fadeIn.fourth {
  -webkit-animation-delay: 1s;
  -moz-animation-delay: 1s;
  animation-delay: 1s;
}

/* Simple CSS3 Fade-in Animation */
.underlineHover:after {
  display: block;
  left: 0;
  bottom: -10px;
  width: 0;
  height: 2px;
  background-color: #56baed;
  content: "";
  transition: width 0.2s;
}

.underlineHover:hover {
  color: #0d0d0d;
}

.underlineHover:hover:after{
  width: 100%;
}



/* OTHERS */

*:focus {
    outline: none;
}

#icon {
  width:60%;
}
    </style>

</head>

  <body>

<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
      <h2> p r o d u c t s </h2>
      <h4> sell&blog </h4>

    <!-- Login Form -->
        {% block content %}
        {% endblock %}
  </div>
</div>


  </body>
</html>

users/templates/users/change_password.html
{% extends 'users/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" class="my-class">
        {% csrf_token %}
{#        <h1 class="h3 mb-3 fw-normal">Для авторизации введите свои данные:</h1>#}
        {% crispy form %}
    </form>
{% endblock %}

users/templates/users/continue_register.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="container">
        <h2 class="active">Ссылка для подтверждения email отправлена на почту</h2>
    </div>
{% endblock %}

users/templates/users/email_reset.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" class="my-class">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Для авторизации введите свои данные:</h1>
        {% crispy form %}
        <a class="btn btn-link" href="{% url 'users:password_reset' %}">Восстановить пароль</a>
        <br>
        <a class="btn btn-link" href="{% url 'users:register' %}">Зарегистрироваться</a>
    </form>
{% endblock %}

users/templates/users/logout.html
{% extends 'users/base.html' %}
{% block content %}
<div class="container">
    <div class="card text-center">
        <h2 class="active"> See you later, alligator! </h2>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
   <form method="post" enctype="multipart/form-data">
       {% csrf_token %}
       {% crispy form %}
   </form>
{% endblock %}

users/templates/users/registration_failed.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="container">
        <h2>Что-то пошло не так</h2>
    <br>
        <a class="underlineHover" href="{% url 'users:register' %}"> Попробовать еще раз </a>
        <a class="underlineHover" href="{% url 'products:records' %}"> Перейти к блогу без регистрации </a>
    </div>
{% endblock %}

users/templates/users/reset_complete.html
{% extends 'users/base.html' %}

{% block content %}
    <h2 class="active">Создан новый пароль</h2>
    <a href="{% url 'products:index' %}" class="btn btn-link">
        Перейти к продуктам
    </a>

{% endblock %}

users/templates/users/reset_confirm.html
{% extends 'users/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Введите новый пароль</h1>
        {% crispy form %}
    </form>
{% endblock %}

users/templates/users/reset_done.html
{% extends 'users/base.html' %}

{% block content %}
    <h2 class="active">Ссылка выслана на почту</h2>
    <a href="{% url 'products:records' %}" class="btn btn-link">
        Вернуться к блогу
    </a>

{% endblock %}

users/templates/users/reset_password.html
{% extends 'users/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" class="my-class">
        {% csrf_token %}
        {% crispy form %}

        <br>
        <a class="btn btn-link" href="{% url 'users:login' %}">Вернуться</a>
    </form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy form %}
    </form>

{% endblock %}