app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.cache import cache_page

from app.apps import AppConfig
from app.views import contacts, ProductListView, ProductDetailView, \
    RecordCreateView, RecordUpdateView, RecordListView, RecordDetailView, \
    RecordDeleteView, ProductCreateView, ProductUpdateWithVersionView, \
    ProductDeleteView, change_is_published, ProductDescriptionUpdateView, \
    ProductCategoryUpdateView, CategoryListView

app_name = AppConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', login_required(contacts), name='contacts'),
    path('product_create/', login_required(ProductCreateView.as_view()), name='create_product'),
    path('product_update/<int:pk>/', login_required(ProductUpdateWithVersionView.as_view()), name='update_product'),
    path('product_update_description/<int:pk>/', login_required(ProductDescriptionUpdateView.as_view()), name='update_product_description'),
    path('product_update_category/<int:pk>/', login_required(ProductCategoryUpdateView.as_view()), name='update_product_category'),
    path('list_category/', login_required(CategoryListView.as_view()), name='list_category'),
    path('<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_card'),
    path('is_published/<int:pk>/', change_is_published, name='change_is_published'),
    path('product_delete/<int:pk>/', login_required(ProductDeleteView.as_view()), name='delete_product'),
    path('records/', RecordListView.as_view(), name='records'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_card'),
    path('records_create/', RecordCreateView.as_view(), name='create_record'),
    path('records_update/<slug:slug>/', RecordUpdateView.as_view(), name='update_record'),
    path('records_delete/<slug:slug>/', RecordDeleteView.as_view(), name='delete_record'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, PasswordChangeView
from django.urls import path
from users.apps import UsersConfig
from users.views import CustomLoginView, UserEditProfileView, \
    CustomRegisterView, CustomPasswordChangeView, user_activation, \
    registration, registration_failed, CustomPasswordResetView, \
    CustomPasswordResetConfirmView, CustomPasswordResetDoneView, \
    CustomPasswordResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', login_required(UserEditProfileView.as_view()), name='profile'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('password/', CustomPasswordChangeView.as_view(), name='reset_password'),
    path('activate/<str:token>/', user_activation, name='activate'),
    path('register_continue/', registration, name='continue_registration'),
    path('register_failed/', registration_failed, name='registration_failed'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<uidb64>/confirm/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

app/templates/app/includes/main_menu.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Меню</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'products:index' %}">Список продуктов</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'products:list_category' %}">Категории</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'products:records' %}">Записи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:contacts' %}">Оставить контакты</a>
        </li>

          </ul>
        <div class="float-end">
            {% if user.is_authenticated %}
            <a class="btn btn-outline-info" href="{% url 'users:profile' %}">Профиль</a>
            |
            <a class="btn btn-outline-info" href="{% url 'users:logout' %}">Выйти</a>
            {% else %}
            <a class="btn btn-outline-info" href="{% url 'users:login' %}">Войти</a>
                |
            <a class="btn btn-outline-info" href="{% url 'users:register' %}">Зарегистрироваться</a>
            {% endif %}
        </div>
        </li>

      </ul>
    </div>
  </div>
</nav>