app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.cache import cache_page

from app.apps import AppConfig
from app.views import contacts, ProductListView, ProductDetailView, \
    RecordCreateView, RecordUpdateView, RecordListView, RecordDetailView, \
    RecordDeleteView, ProductCreateView, ProductUpdateWithVersionView, \
    ProductDeleteView, change_is_published, ProductDescriptionUpdateView, \
    ProductCategoryUpdateView, CategoryListView

app_name = AppConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', login_required(contacts), name='contacts'),
    path('product_create/', login_required(ProductCreateView.as_view()), name='create_product'),
    path('product_update/<int:pk>/', login_required(ProductUpdateWithVersionView.as_view()), name='update_product'),
    path('product_update_description/<int:pk>/', login_required(ProductDescriptionUpdateView.as_view()), name='update_product_description'),
    path('product_update_category/<int:pk>/', login_required(ProductCategoryUpdateView.as_view()), name='update_product_category'),
    path('list_category/', login_required(CategoryListView.as_view()), name='list_category'),
    path('<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_card'),
    path('is_published/<int:pk>/', change_is_published, name='change_is_published'),
    path('product_delete/<int:pk>/', login_required(ProductDeleteView.as_view()), name='delete_product'),
    path('records/', RecordListView.as_view(), name='records'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_card'),
    path('records_create/', RecordCreateView.as_view(), name='create_record'),
    path('records_update/<slug:slug>/', RecordUpdateView.as_view(), name='update_record'),
    path('records_delete/<slug:slug>/', RecordDeleteView.as_view(), name='delete_record'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.conf import settings
from django.db import models
from pytils.translit import slugify

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    PUBLISHED = 'published'
    NOT_PUBLISHED = 'not published'
    PUBLISH_CHOICES = [(PUBLISHED, 'опубликован'), (NOT_PUBLISHED, 'не опубликован')]

    name = models.CharField(max_length=250, verbose_name='Название')
    description = models.CharField(max_length=500, verbose_name='Описание')
    image = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.FloatField(verbose_name='Цена за покупку')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE)
    is_published = models.CharField(max_length=20, choices=PUBLISH_CHOICES, default=NOT_PUBLISHED)
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    changed_date = models.DateField(auto_now=True, verbose_name='Дата последнего изменения')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('pk',)
        permissions = [
            (
                'set_published',
                'Can publish product'
            ),
            (
                'change_description',
                'Can change product description'
            ),
            (
                'change_category',
                'Can change product category'
            )
        ]

    def __str__(self):
        return self.name


class Record(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=200, unique=True, verbose_name='Slug')
    content = models.CharField(max_length=500, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='records/', **NULLABLE, verbose_name='Превью')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    published = models.BooleanField(verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Version(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название версии')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=1, verbose_name='Продукт')
    is_active = models.BooleanField(verbose_name='Текущая версия')

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

    def __str__(self):
        return self.name

base/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'

            field.help_text = ''

base/views.py
from django.shortcuts import render

# Create your views here.

app/templates/app/base.html
{% load static %}

<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>app</title>
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
  </head>
  <body>
  {% include 'app/includes/main_menu.html' %}
    {% block content %}
    {% endblock %}
  <br>
    <script src="{% static "js/bootstrap.bundle.js" %} "> </script>
  </body>
</html>

app/templates/app/category_list.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="container-sm">
        <h1 class="text-center">Список категорий</h1>
      <table class="table">
        <thead>
          <tr>

            <th scope="col">ID</th>
            <th scope="col">Название</th>
            <th scope="col">Описание</th>
          </tr>
        </thead>
        <tbody class="table-group-divider table-divider-primary">

          {% for item in object_list %}
          <tr>
            <th scope="row">{{ item.pk }}</th>
            <td>{{ item.name }}</td>
            <td>{{ item.description|truncatechars:100 }}</td>
         </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

app/templates/app/contacts.html
{% extends 'app/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3">
            <div class="container">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Ваше имя</label>
                        <textarea class="form-control" name="name" id="exampleFormControlTextarea1" rows="1"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Ваш email</label>
                        <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Ваше сообщение</label>
                        <textarea class="form-control" name="message" id="exampleFormControlTextarea1" rows="3"></textarea>
                        <br>
                        <button type="submit" class="btn btn-secondary">Отправить</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% block content %}
<div class="container">
        <h1 class="text-center">Список продуктов</h1>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Название</th>
            <th scope="col">Описание</th>
            <th scope="col">Категория</th>
            <th scope="col">Цена</th>
          </tr>
        </thead>
        <tbody class="table-group-divider table-divider-primary">

          {% for item in object_list %}
          <tr>
            <th scope="row">{{ item.pk }}</th>
            <td>{{ item.name }}</td>
            <td>{{ item.description|truncatechars:100 }}</td>
            <td>{{ item.category.name }}</td>
            <td>{{ item.price }}</td>
              <td><a href="{% url 'products:product_card' item.pk %}" class="btn btn-secondary">Перейти к товару</a></td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

app/templates/app/product_card.html
{% extends 'app/base.html' %}

{% block content %}
    {% load tagss %}
    <div class="container">
        <div class="card text-center">
          <div class="card-header">
              {{ object.name }}
          </div>
          <div class="card-body">
            <h5 class="card-title">Цена: {{ object.price }}</h5>
              <img src="{% mediapath object.image %}"  class="rounded mx-auto d-block" alt="" height="300">
            <p class="card-text">Описание: {{ object.description }}</p>
            <a href="{% url 'products:index' %}" class="btn btn-secondary">Все товары</a>
          </div>
          <div class="card-footer text-muted">
            Создан: {{ object.created_date }}
              <br>
              Изменен: {{ object.changed_date }}
          </div>
        </div>
    </div>>
{% endblock %}

app/templates/app/product_category.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="container-sm">
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-outline-primary" type="submit">Сохранить</button>
        </form>
    </div>
{% endblock %}

app/templates/app/product_description.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="container-sm">
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-outline-primary" type="submit">Сохранить</button>
        </form>
    </div>
{% endblock %}

app/templates/app/product_detail.html
{% extends 'app/base.html' %}

{% block content %}
    {% load tagss %}
    <div class="container">
        <div class="card text-center">
            <div class="card-header">
                {{ object.name }}
            </div>
            <div class="card-body">
                <h5 class="card-title">Цена: {{ object.price }}</h5>
                <img src="{% mediapath object.image %}" class="rounded mx-auto d-block" alt="" height="300">
                <p class="card-text">Описание: {{ object.description }}</p>
                {% if perms.app.change_description %}
                    <a href="{% url 'products:update_product_description' object.pk %}" class="btn btn-outline-secondary">Изменить описание</a>
                {% endif %}

            <p class="card-text">Категория: {{ object.category.name }}</p>
            {% if perms.app.change_category %}
                    <a href="{% url 'products:update_product_category' object.pk %}" class="btn btn-outline-secondary">Изменить категорию</a>
                {% endif %}
                {% if perms.app.change_product or object.user == user %}
                    <a href="{% url 'products:update_product' object.pk %}" class="btn btn-outline-secondary">Изменить
                        продукт</a>
                {% endif %}
                {% if perms.app.delete_product %}
                    <a href="{% url 'products:delete_product' object.pk %}" class="btn btn-outline-danger">Удалить
                        продукт</a>
                {% endif %}
                <br><br>
                <a href="{% url 'products:index' %}" class="btn btn-secondary">Все товары</a>
            </div>
            <div class="card-footer text-muted">
                Создан: {{ object.created_date }}
                <br>
                Изменен: {{ object.changed_date }}
                <br>
                Товар {{ object.get_is_published_display }}
                {% if perms.app.set_published %}
                    {% if object.is_published == 'published' %}
                        <a href="{% url 'app:change_is_published' object.pk %}" class="btn btn-outline-danger">Снять с
                            публикации</a>
                    {% else %}
                        <a href="{% url 'app:change_is_published' object.pk %}" class="btn btn-outline-primary">Опубликовать</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>>
{% endblock %}

app/templates/app/product_form.html
{% extends 'app/base.html' %}

{% block content %}
    <br>
    <div class="container">
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-danger" type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

app/templates/app/product_list.html
{% extends 'app/base.html' %}
{% block content %}
<div class="container">
        <h1 class="text-center">Список продуктов</h1>
      <table class="table">
        <thead>
          <tr>

            <th scope="col">ID</th>
              <th scope="col"> </th>
            <th scope="col">Название</th>
            <th scope="col">Описание</th>
            <th scope="col">Категория</th>
            <th scope="col">Цена</th>
              <th scope="col">Версия</th>
          </tr>
        </thead>
        <tbody class="table-group-divider table-divider-primary">

          {% for item in object_list %}
          <tr>
            <th scope="row">{{ item.pk }}</th>
          <td>

              {% if perms.app.set_published %}
                    {% if item.is_published == 'published' %}
                        <a href="{% url 'app:change_is_published' item.pk %}" class="btn btn-outline-danger">X</a>
                    {% else %}
                        <a href="{% url 'app:change_is_published' item.pk %}" class="btn btn-outline-primary">V</a>
                    {% endif %}
                {% endif %}
          </td>
            <td>{{ item.name }}</td>
            <td>{{ item.description|truncatechars:100 }}</td>
            <td>{{ item.category.name }}</td>
            <td>{{ item.price }}</td>
              <td>
                  {% for v in item.version_set.all %}
                      {% if v.is_active %}
                      {{ v.name }}
                      {% endif %}
                  {% endfor %}

              </td>
              <td><a href="{% url 'products:product_card' item.pk %}" class="btn btn-secondary">Перейти к товару</a></td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
        <div class="container" style="text-align: center">
            {% if user.is_authenticated %}
                <a href="{% url 'products:create_product' %}" class="btn btn-outline-secondary">Создать продукт</a>

            {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/app/product_with_version_form.html
{% extends 'app/base.html' %}

{% block content %}
    <br>
    <div class="container">
    <form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-danger" type="submit">Сохранить</button>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-body">

                    <div class="formset">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            <div class="formset_row">
                            {% for field in form.visible_fields %}
                                <div class="formset-col">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if not forloop.last %}
                                    {{ field.label }}
                                {% endif %}
                                {{ field }}
                                </div>
                            {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
    <script>
        $('.formset_row').formset({
            addText: '<span class="btn btn-outline-secondary">Добавить</span>',
            deleteText: '<span class="btn btn-outline-secondary">Удалить</span>',
            prefix: 'tag_set'
        });
    </script>
    </div>
{% endblock %}

app/templates/app/record_detail.html
{% extends 'app/base.html' %}

{% block content %}
    {% load tagss %}
    <div class="container">
        <div class="card text-center">
          <div class="card-header">
              {{ object.title }}
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ object.content }}</h5>
              <img src="{% mediapath object.preview %}"  class="rounded mx-auto d-block" alt="" height="300">
            <p class="card-text">Просмотры: {{ object.views_count }}</p>
              {% if perms.app.change_record %}
              <a href="{% url 'products:update_record' object.slug %}" class="btn btn-outline-secondary">Изменить запись</a>
              {% endif %}
                {% if perms.app.delete_record %}
              <a href="{% url 'products:delete_record' object.slug %}" class="btn btn-outline-danger">Удалить запись</a>
              {% endif %}
              <br><br>
              <a href="{% url 'products:records' %}" class="btn btn-secondary">Все записи</a>
          </div>
          <div class="card-footer text-muted">
            Создана: {{ object.created_date }}
              <br>
              Опубликована: {{ object.published }}
          </div>
        </div>
    </div>>
{% endblock %}

app/templates/app/record_form.html
{% extends 'app/base.html' %}

{% block content %}
    <br>
    <div class="container">
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-danger" type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

app/templates/app/record_list.html
{% extends 'app/base.html' %}
{% block content %}
    {% load tagss %}
    <div class="container">
        <h1 class="text-center">Список записей</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col" style="text-align: center">ID</th>
                <th scope="col" style="text-align: center">Заголовок</th>
                <th scope="col" style="text-align: center">Содержание</th>
                <th scope="col" style="text-align: center">Превью</th>
                <th scope="col">Просмотры</th>

            </tr>
            </thead>
            <tbody class="table-group-divider table-divider-primary">

            {% for item in object_list %}
                {% if item.published == True %}
                    <tr>
                        <th scope="row">{{ item.pk }}</th>
                        <td>{{ item.title }}</td>
                        <td>{{ item.content|truncatechars:100 }}</td>
                        <td>
                            <img src="{% mediapath item.preview %}" class="rounded mx-auto d-block" alt="" height="100">
                        </td>
                        <td style="text-align: center">{{ item.views_count }}</td>
                        <td><a href="{% url 'products:record_card' item.slug %}" class="btn btn-secondary">Перейти к
                            записи</a></td>

                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <div class="container" style="text-align: center">
            {% if perms.app.add_record %}
                <a href="{% url 'products:create_record' %}" class="btn btn-outline-secondary">Создать запись</a>
            {% endif %}
        </div>
    </div>
{% endblock %}